name: pieklo_server_flutter
description: "Pieklo Server"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-153.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  ffi: ^2.1.2
  flutter_blue_plus: ^1.32.8
  flutter_riverpod: ^2.5.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Light.ttf
          weight: 200
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Regular.ttf
          weight: 400
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Medium.ttf
          weight: 500
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Bold.ttf
          weight: 700

